In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
import numpy as np
# read csv
df = pd.read_csv("diabetes.csv")
X = df.iloc[:,0:8].values #tap du lieu train,test
y = df.iloc[:,8].values #validation

X_train,X_test, y_train, y_test = train_test_split(X,y)
print("X_train {}".format(X_train))
print("X_test {}".format(X_test))
print("y_train {}".format(y_train))
print("y_test {}".format(y_test))
clf = GaussianNB() # classifer
clf.fit(X_train,y_train)
print(clf)
y_predict = clf.predict(X_test)
print("predict:{}".format(y_predict))

#  count number predict accuracy (chinh xac)
predict_accuracy = [np.round(value) for value in y_predict]
accuracy = accuracy_score(y_test, predict_accuracy)
print("accuracy:%.2f" %(accuracy*100))
df.head()

X_train [[  0.    102.     78.    ...  34.5     0.238  24.   ]
 [  0.     78.     88.    ...  36.9     0.434  21.   ]
 [ 10.    133.     68.    ...  27.      0.245  36.   ]
 ...
 [  2.    105.     75.    ...  23.3     0.56   53.   ]
 [  0.    100.     70.    ...  30.8     0.597  21.   ]
 [  3.    108.     62.    ...  26.      0.223  25.   ]]
X_test [[6.00e+00 1.48e+02 7.20e+01 ... 3.36e+01 6.27e-01 5.00e+01]
 [6.00e+00 1.07e+02 8.80e+01 ... 3.68e+01 7.27e-01 3.10e+01]
 [1.00e+00 1.08e+02 8.80e+01 ... 2.71e+01 4.00e-01 2.40e+01]
 ...
 [2.00e+00 1.55e+02 5.20e+01 ... 3.87e+01 2.40e-01 2.50e+01]
 [1.00e+00 1.36e+02 7.40e+01 ... 3.74e+01 3.99e-01 2.40e+01]
 [6.00e+00 9.20e+01 6.20e+01 ... 3.20e+01 8.50e-02 4.60e+01]]
y_train [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0
 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0
 1 1 0 1 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 0 1
 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1