In [3]:
import numpy as np

print(np.random.seed(seed =123))


None


In [9]:
sk_id_curr = np.array(10)
print (sk_id_curr)

# Number of dimensions (số chiều)
print ("sk_id_curr ndim: ", sk_id_curr.ndim)

# Dimensions
print ("sk_id_curr shape:", sk_id_curr.shape)

# Size of elements
print ("sk_id_curr size: ", sk_id_curr.size)

# Data type
print ("sk_id_curr dtype: ", sk_id_curr.dtype)

10
sk_id_curr ndim:  0
sk_id_curr shape: ()
sk_id_curr size:  1
sk_id_curr dtype:  int32


1 D array


In [23]:
a = np.array([1,2,3,4,4,5])
print ("sk_id_curr:", a)
print ("sk_id_curr ndim: ", a.ndim)
print ("sk_id_curr shape:", a.shape)
print ("sk_id_curr size: ", a.size)
print ("sk_id_curr dtype: ", a.dtype)

sk_id_curr: [1 2 3 4 4 5]
sk_id_curr ndim:  1
sk_id_curr shape: (6,)
sk_id_curr size:  6
sk_id_curr dtype:  int32


In [25]:
a = np.array([[10,20],[10,30],[1,2]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(3, 2)
6
int32


In [26]:
print ("np.zeros((2,2)):", np.zeros((2,2)))
print ("np.ones((2,2)):", np.ones((2,2)))
print ("np.eye((2)):", np.eye((2)))
print ("np.random.random((2,2)):", np.random.random((2,2)))


np.zeros((2,2)): [[0. 0.]
 [0. 0.]]
np.ones((2,2)): [[1. 1.]
 [1. 1.]]
np.eye((2)): [[1. 0.]
 [0. 1.]]
np.random.random((2,2)): [[0.69646919 0.28613933]
 [0.22685145 0.55131477]]


In [27]:
sk_id_curr = np.array([[100001, 100005, 111111], [100013, 100028, 222222], [100038, 100042, 333333]])
print (sk_id_curr)
print ("sk_id_curr column 1: ", sk_id_curr[:, 1]) 
print ("sk_id_curr row 0: ", sk_id_curr[0, :]) 
print ("sk_id_curr rows 0,1,2 & cols 1,2:", sk_id_curr[:3, 1:3]) 

[[100001 100005 111111]
 [100013 100028 222222]
 [100038 100042 333333]]
sk_id_curr column 1:  [100005 100028 100042]
sk_id_curr row 0:  [100001 100005 111111]
sk_id_curr rows 0,1,2 & cols 1,2: [[100005 111111]
 [100028 222222]
 [100042 333333]]


In [28]:
sk_id_curr = np.array([[100001, 100005, 111111], [100013, 100028, 222222], [100038, 100042, 333333]])
print ("sk_id_curr:", sk_id_curr)
print ("sk_id_curr > 111111:", sk_id_curr > 111111)
print ("sk_id_curr[sk_id_curr > 111111]:", sk_id_curr[sk_id_curr > 111111])

sk_id_curr: [[100001 100005 111111]
 [100013 100028 222222]
 [100038 100042 333333]]
sk_id_curr > 111111: [[False False False]
 [False False  True]
 [False False  True]]
sk_id_curr[sk_id_curr > 111111]: [222222 333333]


In [34]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%

In [98]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[4,5],[6,7]], dtype= np.float64)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.exp(x))
print(x==y)
print(x<2)
print(x[x<4])
print(np.array_equal(x,y))

[[ 5.  7.]
 [ 9. 11.]]
[[-3. -3.]
 [-3. -3.]]
[[ 4. 10.]
 [18. 28.]]
[[0.25       0.4       ]
 [0.5        0.57142857]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[False False]
 [False False]]
[[ True False]
 [False False]]
[1. 2. 3.]
False


In [36]:
a= np.array([1,2],dtype=np.float64)
b = np.array([[2,3,1],[1,1,4]], dtype = np.float64)
print(a.dot(b))

[4. 5. 9.]


In [87]:
x= np.array([[1,2],[3,4]])
print( "sum all:",np.sum(x))
print("sum columns:", np.sum(x,axis=0))
print("sum row:", np.sum(x, axis=1))
print(x.min())
print(x.max(axis=0))# rows
print(x.max(axis=1))# columns
print(np.mean(x))
print(np.median(x))

sum all: 10
sum columns: [4 6]
sum row: [3 7]
1
[3 4]
[2 4]
2.5
2.5


In [96]:
x= np.array([[1,2],[3,4]])
y= x.copy()
z=np.copy(x)
print(y)
print(z)
print(x[0,1])
print(x[0,:])

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
2
[1 2]


In [41]:
x= np.array([[1,2],[3,4]])
print("x:",x)
print("chuyen vi x:",x.T)

x: [[1 2]
 [3 4]]
chuyen vi x: [[1 3]
 [2 4]]


In [42]:
x= np.array([[1,2],[3,4]])
y = np.array([5,6])
z=x+y
print(z)

[[ 6  8]
 [ 8 10]]


In [44]:
x= np.array([[1,2],[3,4],[5,6]])
print("x:",x)
print("shape:",x.shape)
y = np.reshape(x, (2,3))
print(y)
print(y.shape)

x: [[1 2]
 [3 4]
 [5 6]]
shape: (3, 2)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [74]:
a = np.ones((2,3,4), dtype= np.int16)
print(a)
print(a.ndim)
b = np.zeros((4,3,2), dtype =np.float64)
print(b)
print(b.ndim)
print(np.arange(10,30,5))
print(np.linspace(0,2,8))
print(np.eye(3))
print(np.random.random((2,3)))
print("empty:",np.empty((3,2)))
c = np.full((4,3),7)#constant
print("full:",c)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
3
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3
[10 15 20 25]
[0.         0.28571429 0.57142857 0.85714286 1.14285714 1.42857143
 1.71428571 2.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.87545684 0.51042234 0.66931378]
 [0.58593655 0.6249035  0.67468905]]
empty: [[0.87545684 0.51042234]
 [0.66931378 0.58593655]
 [0.6249035  0.67468905]]
full: [[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [75]:
 np.info(np.ndarray.dtype)
    

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [120]:
b= np.array([[1,23],[4,5],[6,7]])
e = np.copy(b)
print(e.ravel())#flatern array
print(e.reshape(1,6))
print(e.reshape(2,3))
c = np.append(b, [2,3])
d = np.insert(b,1,[2,3])
print(c)
print(d)

[ 1 23  4  5  6  7]
[[ 1 23  4  5  6  7]]
[[ 1 23  4]
 [ 5  6  7]]
[ 1 23  4  5  6  7  2  3]
[ 1  2  3 23  4  5  6  7]
